---
apiVersion: v1
kind: Service
metadata:
  name: age-detect
spec:
  type: NodePort
  selector:
    app: age-detect
  ports:
    - port: 5000
      nodePort: 30600

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: age-detect
spec:
  replicas: 1  # Initial pod count; HPA will manage scaling
  selector:
    matchLabels:
      app: age-detect
  template:
    metadata:
      labels:
        app: age-detect
    spec:
      containers:
        - name: age-detect
          image: age-detect:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"



